model: "tic_promptmodel_MS"
dataset: ""
dataset_path: "dataset/ARKITSCENES_upsampling/Training/highres_RGB_resized"
depth_train: "dataset/ARKITSCENES_upsampling/Training/lowres_depth_resized"
kodak_path: "dataset/ARKITSCENES_upsampling/Validation/highres_RGB_resized"
depth_test: "dataset/ARKITSCENES_upsampling/Validation/lowres_depth_resized"
input_resolution: 256
epochs: 100
learning_rate: 1.e-4
num_workers: 4
quality_level: 4
batch_size: 8
test_batch_size: 1
aux_learning_rate: 1.e-3
patch_size: 256
cuda: True
gpu_id: 0
save: True
clip_max_norm: 1.0
name: "NAME"
exp_name: "NAME"
seed: 42
root: "/root/path"
checkpoint: "/path/to/checkpoint"
LOCATION: 'prepend'
DEEP: True
NUM_TOKENS: 16
INITIATION: 'random'
PROJECT: -1
DROPOUT: 0.
TRANSFER_TYPE: 'prompt'
ARCHITECT: 'both'
WINDOW: 'same' 
RETURN_ATTENTION: False
MASK_DOWNSAMPLE: 2
